services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
      network: host
    container_name: ${PROJECT_NAME}_backend
    restart: 'no'
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - /app/vendor 
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - selarasa_net

  pos:
    build:
      context: ./frontend-pos
      dockerfile: dockerfile
      network: host
    container_name: ${PROJECT_NAME}_pos
    restart: 'no'
    ports:
      - "5173:5173"
    volumes:
      - ./frontend-pos:/app
      - /app/node_modules 
    command: npm run dev -- --host 0.0.0.0
    networks:
      - selarasa_net

  inventory:
    build:
      context: ./frontend-inventory
      dockerfile: dockerfile
      network: host
    container_name: ${PROJECT_NAME}_inventory
    restart: 'no'
    ports:
      - "5174:5174"
    volumes:
      - ./frontend-inventory:/app
      - /app/node_modules
    command: npm run dev -- --host 0.0.0.0 --port 5174 --strictPort 
    networks:
      - selarasa_net

  db:
    image: postgres:16-alpine
    container_name: ${PROJECT_NAME}_db
    restart: 'no'
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - selarasa_net

  redis:
    image: redis:alpine
    container_name: ${PROJECT_NAME}_redis
    restart: 'no'
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - selarasa_net

networks:
  selarasa_net:
    driver: bridge

volumes:
  db_data:
  redis_data: