FROM dunglas/frankenphp:php8.4

RUN apt-get update && apt-get install -y git unzip curl

RUN install-php-extensions \
    pdo_pgsql \
    mbstring \
    pcntl \
    bcmath \
    gd \
    intl \
    zip \
    redis

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

COPY composer.json composer.lock* ./

COPY . .

RUN composer install --no-interaction --prefer-dist --optimize-autoloader

COPY docker/entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod +x /usr/local/bin/entrypoint.sh

ENTRYPOINT ["entrypoint.sh"]

ENV SERVER_NAME=":8000"